# Generated by Django 6.0.8 on 2026-09-05 11:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('document_type', models.CharField(choices=[('RESUME', 'Resume / CV'), ('CERTIFICATE', 'Certificate'), ('TRANSCRIPT', 'Academic Transcript'), ('ID_PROOF', 'ID Verification Proof'), ('OTHER', 'Other Document')], default='RESUME', max_length=30)),
                ('file_url', models.CharField(max_length=500)),
                ('file_size_bytes', models.PositiveIntegerField(default=0)),
                ('mime_type', models.CharField(default='application/pdf', max_length=100)),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
