import type { Config } from 'tailwindcss';

const config: Config = {
  darkMode: ['class'],
  content: [
    './src/**/*.{js,ts,jsx,tsx,mdx}',
    '../../packages/ui/src/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        'on-primary-container': '#71717A',
        'fg-primary': '#09090B',
        'surface-bright': '#FFFFFF',
        'error-container': '#FEF3C7',
        'on-error': '#09090B',
        'surface-tint': '#27272A',
        'bg-canvas': '#FFFFFF',
        'error': '#B45309',
        'secondary': '#EAB308',
        'bg-surface': '#FFFFFF',
        'secondary-fixed': '#FEF08A',
        'on-surface': '#09090B',
        'secondary-fixed-dim': '#FDE047',
        'surface-container-lowest': '#FFFFFF',
        'surface-container-low': '#FAFAFA',
        'surface': '#FFFFFF',
        'on-primary': '#09090B',
        'on-surface-variant': '#52525B',
        'primary-fixed': '#F4F4F5',
        'outline': '#71717A',
        'on-background': '#09090B',
        'status-success': '#16A34A',
        'primary-fixed-dim': '#E4E4E7',
        'primary': '#09090B',
        'inverse-surface': '#18181B',
        'on-primary-fixed': '#09090B',
        'on-secondary-fixed-variant': '#713F12',
        'fg-secondary': '#27272A',
        'status-danger': '#B45309',
        'on-error-container': '#78350F',
        'bg-subtle': '#F4F4F5',
        'tertiary-fixed': '#FAFAFA',
        'status-warning': '#EAB308',
        'surface-container': '#F4F4F5',
        'on-tertiary-fixed': '#09090B',
        'border-hairline': '#18181B',
        'fg-muted': '#71717A',
        'on-secondary-fixed': '#451A03',
        'surface-variant': '#F4F4F5',
        'on-tertiary-container': '#71717A',
        'outline-variant': '#E4E4E7',
        'tertiary': '#09090B',
        'on-secondary-container': '#09090B',
        'inverse-primary': '#E4E4E7',
        'inverse-on-surface': '#F4F4F5',
        'surface-dim': '#E4E4E7',
        'surface-container-high': '#E4E4E7',
        'border-strong': '#18181B',
        'tertiary-fixed-dim': '#D4D4D8',
        'on-tertiary-fixed-variant': '#52525B',
        'primary-container': '#18181B',
        'secondary-container': '#FACC15',
        'background': '#FFFFFF',
        'on-secondary': '#09090B',
        'tertiary-container': '#27272A',
        'on-tertiary': '#FFFFFF',
        'accent-signal': '#FACC15',
        'accent-signal-hover': '#EAB308',
        'on-primary-fixed-variant': '#52525B',
        'surface-container-highest': '#E4E4E7',
        brand: {
          50: '#f0fdfa',
          100: '#ccfbf1',
          500: '#14b8a6',
          600: '#0d9488',
          700: '#0f766e',
          900: '#134e4a',
        },
      },
      borderRadius: {
        DEFAULT: '0px',
        none: '0px',
        sm: '0px',
        md: '0px',
        lg: '0px',
        xl: '0px',
        full: '9999px',
      },
      spacing: {
        'grid-margin': '32px',
        'hairline': '1px',
        'space-2xs': '2px',
        'space-2xl': '48px',
        'space-xs': '4px',
        'grid-gutter': '24px',
        'space-lg': '24px',
        'space-md': '16px',
        'space-sm': '8px',
        'space-3xl': '64px',
        'grid-margin-mobile': '16px',
        'space-xl': '32px',
        'space-4xl': '96px',
      },
      fontFamily: {
        sans: ['var(--font-inter)', 'Inter', 'sans-serif'],
        mono: ['var(--font-jetbrains)', "'JetBrains Mono'", 'monospace'],
        'body-sm': ['var(--font-inter)', 'Inter', 'sans-serif'],
        'display-hero': ['var(--font-inter)', 'Inter', 'sans-serif'],
        'headline-lg-mobile': ['var(--font-inter)', 'Inter', 'sans-serif'],
        'headline-sm': ['var(--font-inter)', 'Inter', 'sans-serif'],
        'body-lg': ['var(--font-inter)', 'Inter', 'sans-serif'],
        'display-hero-mobile': ['var(--font-inter)', 'Inter', 'sans-serif'],
        'headline-md': ['var(--font-inter)', 'Inter', 'sans-serif'],
        'label-mono': ['var(--font-jetbrains)', "'JetBrains Mono'", 'monospace'],
        'headline-lg': ['var(--font-inter)', 'Inter', 'sans-serif'],
        'body-md': ['var(--font-inter)', 'Inter', 'sans-serif'],
        'metric-tabular': ['var(--font-jetbrains)', "'JetBrains Mono'", 'monospace'],
      },
      fontSize: {
        'body-sm': ['12px', { lineHeight: '18px', letterSpacing: '0em', fontWeight: '400' }],
        'display-hero': ['56px', { lineHeight: '60px', letterSpacing: '-0.04em', fontWeight: '800' }],
        'display-hero-mobile': ['36px', { lineHeight: '40px', letterSpacing: '-0.03em', fontWeight: '800' }],
        'headline-lg-mobile': ['28px', { lineHeight: '32px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-sm': ['18px', { lineHeight: '24px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'body-lg': ['16px', { lineHeight: '26px', letterSpacing: '-0.01em', fontWeight: '400' }],
        'headline-md': ['24px', { lineHeight: '30px', letterSpacing: '-0.02em', fontWeight: '600' }],
        'label-mono': ['11px', { lineHeight: '16px', letterSpacing: '0.06em', fontWeight: '500' }],
        'headline-lg': ['40px', { lineHeight: '44px', letterSpacing: '-0.03em', fontWeight: '700' }],
        'body-md': ['14px', { lineHeight: '22px', letterSpacing: '0em', fontWeight: '400' }],
        'metric-tabular': ['28px', { lineHeight: '32px', letterSpacing: '-0.02em', fontWeight: '600' }],
      },
    },
  },
  plugins: [],
};

export default config;
