# Generated by Django 6.0.8 on 2026-09-05 11:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('industries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('project_type', models.CharField(choices=[('ACADEMIC', 'Academic Project'), ('INDUSTRY_LIVE', 'Industry Live Project'), ('CAPSTONE', 'Capstone Project'), ('OPEN_SOURCE', 'Open Source Contribution')], default='ACADEMIC', max_length=30)),
                ('skills_used', models.JSONField(blank=True, default=list)),
                ('repo_url', models.URLField(blank=True, default='')),
                ('live_demo_url', models.URLField(blank=True, default='')),
                ('media_urls', models.JSONField(blank=True, default=list)),
                ('is_verified', models.BooleanField(default=False)),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('industry_partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sponsored_projects', to='industries.industryprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
