# Generated by Django 6.0.8 on 2026-09-05 11:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('industries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlacementDrive',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('eligible_branches', models.JSONField(blank=True, default=list)),
                ('minimum_cgpa', models.DecimalField(decimal_places=2, default=6.5, max_digits=4)),
                ('package_lpa', models.DecimalField(decimal_places=2, default=12.0, max_digits=5)),
                ('drive_date', models.DateField()),
                ('rounds', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('UPCOMING', 'Upcoming Drive'), ('ONGOING', 'Ongoing Drive'), ('COMPLETED', 'Completed')], default='UPCOMING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placement_drives', to='industries.industryprofile')),
            ],
            options={
                'ordering': ['drive_date'],
            },
        ),
        migrations.CreateModel(
            name='PlacementRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('package_offered_lpa', models.DecimalField(decimal_places=2, default=12.0, max_digits=5)),
                ('status', models.CharField(choices=[('OFFERED', 'Offer Extended'), ('ACCEPTED', 'Offer Accepted'), ('DECLINED', 'Offer Declined')], default='OFFERED', max_length=20)),
                ('offer_letter_url', models.URLField(blank=True, default='')),
                ('offered_at', models.DateTimeField(auto_now_add=True)),
                ('drive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placed_students', to='placements.placementdrive')),
            ],
            options={
                'ordering': ['-offered_at'],
            },
        ),
    ]
