# Generated by Django 6.0.8 on 2026-09-05 11:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SkillPassport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('passport_number', models.CharField(max_length=50, unique=True)),
                ('qr_code_payload', models.TextField(blank=True, default='')),
                ('verified_credentials_snapshot', models.JSONField(blank=True, default=list)),
                ('cryptographic_signature', models.CharField(blank=True, default='', max_length=256)),
                ('is_valid', models.BooleanField(default=True)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-issued_at'],
            },
        ),
    ]
