# Generated by Django 6.0.8 on 2026-09-05 11:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('industries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningResource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('provider', models.CharField(default='Internal Portal', max_length=150)),
                ('type', models.CharField(choices=[('COURSE', 'Online Course'), ('TRAINING', 'Industry Training'), ('WORKSHOP', 'Interactive Workshop'), ('MODULE', 'Self-paced Module')], default='COURSE', max_length=30)),
                ('url', models.URLField(blank=True, default='https://learning.portal.internal')),
                ('duration_hours', models.PositiveIntegerField(default=10)),
                ('difficulty', models.CharField(default='INTERMEDIATE', max_length=30)),
                ('rating', models.FloatField(default=4.8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-rating', 'title'],
            },
        ),
        migrations.CreateModel(
            name='UserLearningProgress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('progress_percentage', models.FloatField(default=0.0)),
                ('status', models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], default='NOT_STARTED', max_length=30)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='IndustryTraining',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('syllabus', models.JSONField(blank=True, default=list)),
                ('duration_weeks', models.PositiveIntegerField(default=4)),
                ('mode', models.CharField(default='ONLINE', max_length=30)),
                ('schedule', models.CharField(default='Weekend Batches', max_length=150)),
                ('max_participants', models.PositiveIntegerField(default=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('industry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainings', to='industries.industryprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
