# Generated by Django 6.0.8 on 2026-09-05 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('learning', '0001_initial'),
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningresource',
            name='skills_targeted',
            field=models.ManyToManyField(blank=True, related_name='learning_resources', to='skills.skill'),
        ),
        migrations.AddField(
            model_name='userlearningprogress',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to='learning.learningresource'),
        ),
    ]
