# Generated by Django 6.0.8 on 2026-09-05 11:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=180, unique=True)),
                ('category', models.CharField(choices=[('PROGRAMMING', 'Programming Languages'), ('FRAMEWORKS', 'Frameworks & Libraries'), ('DATABASES', 'Databases & Storage'), ('CLOUD_DEVOPS', 'Cloud & DevOps'), ('AI_ML', 'Artificial Intelligence & ML'), ('SOFT_SKILLS', 'Soft Skills & Leadership'), ('DOMAIN_KNOWLEDGE', 'Domain Knowledge'), ('OTHER', 'Other')], default='OTHER', max_length=50)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StudentSkill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('proficiency', models.CharField(choices=[('BEGINNER', 'Beginner'), ('INTERMEDIATE', 'Intermediate'), ('ADVANCED', 'Advanced'), ('EXPERT', 'Expert')], default='INTERMEDIATE', max_length=30)),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_score', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_skills', to='skills.skill')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
