# Generated by Django 6.0.8 on 2026-09-05 11:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('snapshot_type', models.CharField(choices=[('INSTITUTION', 'Institution Overview'), ('HEATMAP', 'Skill Demand Heatmap'), ('INDUSTRY', 'Industry Trends')], max_length=30)),
                ('data', models.JSONField(default=dict)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
    ]
