import React from 'react';
import {
  LayoutDashboard,
  SlidersHorizontal,
  Briefcase,
  BookOpen,
  Coins,
  Compass,
  CheckCircle2,
  ShieldCheck,
  AlertTriangle,
  ArrowRight,
  Search,
  Bell,
  Lock,
  Play,
  GraduationCap,
  Network,
  Brain,
  UserSearch,
  Layers,
  FlaskConical,
  Users,
  BarChart3,
  Filter,
  FileText,
  FileBadge,
  Grid,
  Sparkles,
  Download,
  Upload,
  ExternalLink,
  ChevronRight,
  Check,
  X,
  Clock,
  MapPin,
  Calendar,
  Building2,
  Eye,
  HelpCircle,
  Gauge,
  Flag,
  Award,
  CheckSquare,
  Scale,
  Bot,
  DollarSign,
  Link2,
  Send,
  History,
  RotateCcw,
  Plus,
  UploadCloud,
  Copy,
  Share2,
  Zap,
  Code2,
  Shield,
  UserCheck,
  RefreshCw,
  Terminal,
  Cpu,
  Info,
  TrendingUp,
  TrendingDown,
  Flame,
  Handshake,
  type LucideIcon,
} from 'lucide-react';

const iconMap: Record<string, LucideIcon> = {
  // Navigation & Core
  dashboard: LayoutDashboard,
  layoutdashboard: LayoutDashboard,
  tune: SlidersHorizontal,
  settings: SlidersHorizontal,
  sliders: SlidersHorizontal,
  slidershorizontal: SlidersHorizontal,
  sliders_horizontal: SlidersHorizontal,

  // Education & Academics
  school: GraduationCap,
  graduation_cap: GraduationCap,
  graduationcap: GraduationCap,
  education: GraduationCap,
  academic: GraduationCap,

  // Books & Documentation
  menu_book: BookOpen,
  book_open: BookOpen,
  bookopen: BookOpen,
  book: BookOpen,
  article: FileText,
  assignment: FileText,
  file_text: FileText,
  filetext: FileText,
  document: FileText,
  badge: FileBadge,
  file_badge: FileBadge,
  filebadge: FileBadge,
  certificate: FileBadge,

  // Business, Work & Partners
  handshake: Handshake,
  partnership: Handshake,
  collaboration: Handshake,
  briefcase: Briefcase,
  business_center: Briefcase,
  work_history: Briefcase,
  building: Building2,
  building2: Building2,

  // Grants, Tokens & Currency
  token: Coins,
  coins: Coins,
  payments: DollarSign,
  dollar_sign: DollarSign,
  dollarsign: DollarSign,
  request_quote: Coins,

  // Science, Tech & Lab
  biotech: FlaskConical,
  flask_conical: FlaskConical,
  flaskconical: FlaskConical,
  flask: FlaskConical,
  science: FlaskConical,
  psychology: Brain,
  brain: Brain,
  engineering: Cpu,
  cpu: Cpu,
  terminal: Terminal,
  code: Code2,
  code2: Code2,
  hub: Network,
  network: Network,
  layers: Layers,

  // People & Sessions
  groups: Users,
  users: Users,
  family_restroom: Users,
  co_present: Users,
  person_search: UserSearch,
  user_search: UserSearch,
  usersearch: UserSearch,
  person_pin: UserCheck,
  user_check: UserCheck,
  usercheck: UserCheck,

  // Security & Verification
  shield: Shield,
  verified: CheckCircle2,
  verified_user: ShieldCheck,
  shield_check: ShieldCheck,
  shieldcheck: ShieldCheck,
  check_circle: CheckCircle2,
  checkcircle: CheckCircle2,
  task_alt: CheckCircle2,
  lock: Lock,

  // Time & Scheduling
  clock: Clock,
  timer: Clock,
  schedule: Clock,
  calendar: Calendar,
  calendar_month: Calendar,
  history: History,

  // Analytics & Gauges
  analytics: BarChart3,
  bar_chart: BarChart3,
  barchart: BarChart3,
  speed: Gauge,
  gauge: Gauge,
  award: Award,
  military_tech: Award,
  rule: CheckSquare,
  check_square: CheckSquare,
  checksquare: CheckSquare,
  balance: Scale,
  scale: Scale,
  flag: Flag,

  // UI & Controls
  travel_explore: Compass,
  compass: Compass,
  warning: AlertTriangle,
  error: AlertTriangle,
  error_outline: AlertTriangle,
  alert: AlertTriangle,
  arrow_forward: ArrowRight,
  arrowright: ArrowRight,
  search: Search,
  notifications: Bell,
  bell: Bell,
  play_arrow: Play,
  play: Play,
  filter: Filter,
  filter_alt: Filter,
  grid: Grid,
  grid_view: Grid,
  sparkles: Sparkles,
  download: Download,
  upload: Upload,
  upload_file: UploadCloud,
  upload_cloud: UploadCloud,
  uploadcloud: UploadCloud,
  external: ExternalLink,
  open_in_new: ExternalLink,
  launch: ExternalLink,
  chevron_right: ChevronRight,
  check: Check,
  close: X,
  location: MapPin,
  map_pin: MapPin,
  mappin: MapPin,
  quiz: HelpCircle,
  help: HelpCircle,
  help_circle: HelpCircle,
  visibility: Eye,
  eye: Eye,
  bot: Bot,
  smart_toy: Bot,
  link: Link2,
  link2: Link2,
  send: Send,
  replay: RotateCcw,
  rotate_ccw: RotateCcw,
  rotateccw: RotateCcw,
  add: Plus,
  plus: Plus,
  content_copy: Copy,
  copy: Copy,
  share: Share2,
  share2: Share2,
  bolt: Zap,
  zap: Zap,
  refresh: RefreshCw,
  sync: RefreshCw,
  refresh_cw: RefreshCw,
  refreshcw: RefreshCw,
  info: Info,
  trending_up: TrendingUp,
  trendingup: TrendingUp,
  trending_down: TrendingDown,
  trendingdown: TrendingDown,
  flame: Flame,
};

export interface IconProps {
  name: string;
  size?: number;
  className?: string;
}

export const Icon: React.FC<IconProps> = ({ name, size = 18, className = '' }) => {
  if (!name) return null;

  const cleanName = name.toLowerCase().trim();
  const normalizedKey = cleanName.replace(/[-_]/g, '');

  const Component = iconMap[cleanName] || iconMap[normalizedKey];
  if (Component) {
    return <Component size={size} className={className} />;
  }

  return (
    <span
      className={`material-symbols-outlined inline-block align-middle ${className}`}
      style={{ fontSize: `${size}px`, lineHeight: 1 }}
    >
      {name}
    </span>
  );
};
