import React from 'react';
import {
  LayoutDashboard,
  SlidersHorizontal,
  Briefcase,
  BookOpen,
  Coins,
  Compass,
  CheckCircle2,
  ShieldCheck,
  AlertTriangle,
  ArrowRight,
  Search,
  Bell,
  Lock,
  Play,
  GraduationCap,
  Network,
  Brain,
  UserSearch,
  Layers,
  FlaskConical,
  Users,
  BarChart3,
  Filter,
  FileText,
  FileBadge,
  Grid,
  Sparkles,
  Download,
  Upload,
  ExternalLink,
  ChevronRight,
  Check,
  X,
  Clock,
  MapPin,
  Calendar,
  Building2,
  Eye,
  HelpCircle,
  Gauge,
  Flag,
  Award,
  CheckSquare,
  Scale,
  Bot,
  DollarSign,
  Link2,
  Send,
  History,
  RotateCcw,
  Plus,
  UploadCloud,
  Copy,
  Share2,
  Zap,
  Code2,
  Shield,
  UserCheck,
  RefreshCw,
  Terminal,
  Cpu,
  Info,
  TrendingUp,
  TrendingDown,
  Flame,
  type LucideIcon,
} from 'lucide-react';

const iconMap: Record<string, LucideIcon> = {
  dashboard: LayoutDashboard,
  tune: SlidersHorizontal,
  work_history: Briefcase,
  menu_book: BookOpen,
  token: Coins,
  travel_explore: Compass,
  verified: CheckCircle2,
  verified_user: ShieldCheck,
  warning: AlertTriangle,
  check_circle: CheckCircle2,
  task_alt: CheckCircle2,
  arrow_forward: ArrowRight,
  search: Search,
  notifications: Bell,
  lock: Lock,
  play_arrow: Play,
  play: Play,
  school: GraduationCap,
  hub: Network,
  psychology: Brain,
  person_search: UserSearch,
  layers: Layers,
  biotech: FlaskConical,
  groups: Users,
  family_restroom: Users,
  analytics: BarChart3,
  filter_alt: Filter,
  article: FileText,
  badge: FileBadge,
  grid_view: Grid,
  sparkles: Sparkles,
  download: Download,
  upload: Upload,
  external: ExternalLink,
  open_in_new: ExternalLink,
  launch: ExternalLink,
  chevron_right: ChevronRight,
  check: Check,
  close: X,
  clock: Clock,
  timer: Clock,
  location: MapPin,
  calendar: Calendar,
  calendar_month: Calendar,
  building: Building2,
  
  // Custom mapped icons for readiness, assessments, and portfolio
  quiz: HelpCircle,
  visibility: Eye,
  eye: Eye,
  speed: Gauge,
  flag: Flag,
  military_tech: Award,
  award: Award,
  rule: CheckSquare,
  balance: Scale,
  smart_toy: Bot,
  bot: Bot,
  payments: DollarSign,
  link: Link2,
  send: Send,
  history: History,
  replay: RotateCcw,
  add: Plus,
  upload_file: UploadCloud,
  content_copy: Copy,
  copy: Copy,
  share: Share2,
  bolt: Zap,
  code: Code2,
  shield: Shield,
  person_pin: UserCheck,
  refresh: RefreshCw,
  sync: RefreshCw,
  terminal: Terminal,
  cpu: Cpu,
  info: Info,
  trending_up: TrendingUp,
  trending_down: TrendingDown,
  flame: Flame,
};

export interface IconProps {
  name: string;
  size?: number;
  className?: string;
}

export const Icon: React.FC<IconProps> = ({ name, size = 18, className = '' }) => {
  const Component = iconMap[name.toLowerCase()];
  if (Component) {
    return <Component size={size} className={className} />;
  }

  return (
    <span
      className={`material-symbols-outlined inline-block align-middle ${className}`}
      style={{ fontSize: `${size}px`, lineHeight: 1 }}
    >
      {name}
    </span>
  );
};
