# Generated by Django 6.0.8 on 2026-09-05 11:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, unique=True)),
                ('slug', models.SlugField(max_length=150, unique=True)),
                ('icon', models.CharField(default='award', max_length=50)),
                ('description', models.TextField(blank=True, default='')),
                ('points_reward', models.PositiveIntegerField(default=100)),
                ('category', models.CharField(choices=[('ASSESSMENT', 'Assessment Mastery'), ('PROJECT', 'Project Excellence'), ('MENTORSHIP', 'Mentorship & Collab'), ('COMMUNITY', 'Community Engagement'), ('SPECIAL', 'Special Achievement')], default='ASSESSMENT', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserGamification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_points', models.PositiveIntegerField(default=150)),
                ('current_level', models.PositiveIntegerField(default=1)),
                ('rank', models.PositiveIntegerField(default=1)),
                ('streak_days', models.PositiveIntegerField(default=3)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('badges', models.ManyToManyField(blank=True, related_name='earned_by', to='gamification.badge')),
            ],
            options={
                'ordering': ['-total_points'],
            },
        ),
    ]
