# Generated by Django 6.0.8 on 2026-09-06 17:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='guardian_confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='guardian_consent_status',
            field=models.CharField(choices=[('not_required', 'Not Required'), ('pending', 'Pending Confirmation'), ('confirmed', 'Confirmed & Locked')], default='not_required', max_length=30),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='guardian_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='guardian_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='guardian_token',
            field=models.CharField(blank=True, db_index=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='passport_hash',
            field=models.CharField(blank=True, default='', max_length=66),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='portfolio_slug',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='student_type',
            field=models.CharField(choices=[('college', 'College Student'), ('alumni', 'Alumni'), ('pre_college', 'Pre-College (High School)')], default='college', max_length=30),
        ),
        migrations.CreateModel(
            name='StudentChatSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('messages', models.JSONField(blank=True, default=list)),
                ('daily_count', models.PositiveIntegerField(default=0)),
                ('daily_limit', models.PositiveIntegerField(default=30)),
                ('last_reset_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chat_session', to='students.studentprofile')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
