# Generated by Django 6.0.8 on 2026-09-05 11:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActionPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target_role', models.CharField(default='Full Stack Developer', max_length=150)),
                ('skill_gap', models.CharField(blank=True, default='', max_length=255)),
                ('priority', models.CharField(choices=[('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], default='HIGH', max_length=20)),
                ('steps', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='CareerPath',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('industry', models.CharField(default='Technology & Software', max_length=150)),
                ('salary_range', models.JSONField(blank=True, default=dict)),
                ('growth_projection', models.CharField(default='High (+22% YoY)', max_length=100)),
                ('core_skills', models.JSONField(blank=True, default=list)),
                ('recommended_steps', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='CareerReadinessScore',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('overall_score', models.PositiveIntegerField(default=75)),
                ('technical_score', models.PositiveIntegerField(default=80)),
                ('soft_skill_score', models.PositiveIntegerField(default=70)),
                ('project_score', models.PositiveIntegerField(default=75)),
                ('certification_score', models.PositiveIntegerField(default=70)),
                ('experience_score', models.PositiveIntegerField(default=65)),
                ('explanation', models.TextField(blank=True, default='')),
                ('calculated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-calculated_at'],
            },
        ),
    ]
