# Generated by Django 6.0.8 on 2026-09-05 11:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicianProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('institution_name', models.CharField(blank=True, default='', max_length=255)),
                ('department', models.CharField(blank=True, default='', max_length=150)),
                ('designation', models.CharField(blank=True, default='Assistant Professor', max_length=100)),
                ('qualifications', models.CharField(blank=True, default='Ph.D.', max_length=255)),
                ('experience_years', models.PositiveIntegerField(default=5)),
                ('areas_of_expertise', models.TextField(blank=True, default='')),
                ('publications', models.TextField(blank=True, default='')),
                ('research_interests', models.TextField(blank=True, default='')),
                ('industry_training_interests', models.TextField(blank=True, default='')),
                ('consultancy_areas', models.TextField(blank=True, default='')),
                ('bio', models.TextField(blank=True, default='')),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
