# Generated by Django 6.0.8 on 2026-09-05 11:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InternshipPosting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('internship_type', models.CharField(choices=[('SUMMER', 'Summer Internship'), ('WINTER', 'Winter Internship'), ('SEMESTER_LONG', 'Semester Long (6 Months)'), ('FACULTY_INTERNSHIP', 'Faculty Industrial Internship')], default='SUMMER', max_length=30)),
                ('weekly_hours', models.PositiveIntegerField(default=40)),
                ('mentorship_provided', models.BooleanField(default=True)),
                ('certificate_provided', models.BooleanField(default=True)),
                ('ppo_eligible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
