export const ROLE_PERMISSIONS: Record<string, string[]> = {
  STUDENT: [
    'view_profile',
    'edit_own_profile',
    'apply_opportunity',
    'take_assessment',
    'view_skill_passport',
    'view_learning_paths',
    'view_own_applications',
    'withdraw_application',
    'access_career_assistant',
  ],
  INDUSTRY: [
    'view_profile',
    'edit_own_profile',
    'post_opportunity',
    'manage_own_opportunities',
    'view_candidates',
    'update_application_status',
    'use_jd_analyzer',
    'view_industry_trends',
  ],
  ACADEMICIAN: [
    'view_profile',
    'edit_own_profile',
    'view_fdp',
    'apply_faculty_internship',
    'mentor_students',
    'verify_student_skills',
    'view_institution_analytics',
  ],
  INSTITUTION_ADMIN: [
    'view_profile',
    'edit_own_profile',
    'view_institution_analytics',
    'view_skill_heatmaps',
    'manage_students',
    'verify_credentials',
    'manage_institution_opportunities',
  ],
  SUPER_ADMIN: [
    'manage_all',
    'manage_users',
    'manage_roles',
    'verify_credentials',
    'view_institution_analytics',
    'view_skill_heatmaps',
    'audit_logs',
    'system_configuration',
  ],
};
