# Generated by Django 6.0.8 on 2026-09-06 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0003_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assessmentattempt',
            old_name='percentage',
            new_name='score_percentage',
        ),
        migrations.RenameField(
            model_name='assessmentattempt',
            old_name='score',
            new_name='score_raw',
        ),
        migrations.RemoveField(
            model_name='assessment',
            name='assessment_type',
        ),
        migrations.RemoveField(
            model_name='assessment',
            name='skills_assessed',
        ),
        migrations.RemoveField(
            model_name='assessment',
            name='total_marks',
        ),
        migrations.RemoveField(
            model_name='assessmentattempt',
            name='passed',
        ),
        migrations.RemoveField(
            model_name='assessmentattempt',
            name='skill_breakdown',
        ),
        migrations.RemoveField(
            model_name='assessmentquestion',
            name='correct_answer',
        ),
        migrations.RemoveField(
            model_name='assessmentquestion',
            name='question_type',
        ),
        migrations.AddField(
            model_name='assessment',
            name='category',
            field=models.CharField(choices=[('technical', 'Technical'), ('aptitude', 'Aptitude & Logic'), ('soft', 'Soft Skills'), ('domain_specific', 'Domain Specific')], default='technical', max_length=30),
        ),
        migrations.AddField(
            model_name='assessment',
            name='skill_tags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='assessment',
            name='slug',
            field=models.SlugField(blank=True, max_length=150, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='total_questions',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='assessmentattempt',
            name='correct_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='assessmentattempt',
            name='time_spent_seconds',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='assessmentattempt',
            name='topic_breakdown',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='assessmentattempt',
            name='total_questions',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='assessmentquestion',
            name='category',
            field=models.CharField(choices=[('technical', 'Technical'), ('aptitude', 'Aptitude & Logic'), ('soft', 'Soft Skills'), ('domain_specific', 'Domain Specific')], default='technical', max_length=30),
        ),
        migrations.AddField(
            model_name='assessmentquestion',
            name='correct_option',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='assessmentquestion',
            name='difficulty',
            field=models.CharField(default='intermediate', max_length=20),
        ),
        migrations.AddField(
            model_name='assessmentquestion',
            name='skill_tag',
            field=models.CharField(default='General', max_length=100),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=15),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='passing_score',
            field=models.PositiveIntegerField(default=70),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='published', max_length=30),
        ),
        migrations.AlterField(
            model_name='assessmentattempt',
            name='status',
            field=models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed'), ('evaluated', 'Evaluated'), ('passed', 'Passed'), ('failed', 'Failed')], default='in_progress', max_length=30),
        ),
    ]
