# Generated by Django 6.0.8 on 2026-09-05 11:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DigitalPortfolio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.SlugField(max_length=100, unique=True)),
                ('custom_theme', models.CharField(default='default', max_length=50)),
                ('achievements', models.JSONField(blank=True, default=list)),
                ('is_public', models.BooleanField(default=True)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-views_count'],
            },
        ),
    ]
