# Generated by Django 6.0.8 on 2026-09-05 11:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SkillGapAnalysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target_role', models.CharField(max_length=150)),
                ('required_skills', models.JSONField(blank=True, default=list)),
                ('matched_skills', models.JSONField(blank=True, default=list)),
                ('missing_skills', models.JSONField(blank=True, default=list)),
                ('readiness_percentage', models.FloatField(default=0.0)),
                ('recommendations', models.JSONField(blank=True, default=list)),
                ('analyzed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-analyzed_at'],
            },
        ),
    ]
