# Generated by Django 6.0.8 on 2026-09-05 11:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('industries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MicroInternship',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('problem_statement', models.TextField()),
                ('deliverables', models.JSONField(blank=True, default=list)),
                ('stipend', models.CharField(default='INR 15,000', max_length=100)),
                ('duration_days', models.PositiveIntegerField(default=21)),
                ('max_applicants', models.PositiveIntegerField(default=5)),
                ('status', models.CharField(choices=[('OPEN', 'Open for Applications'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CLOSED', 'Closed')], default='OPEN', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('industry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='micro_internships', to='industries.industryprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
