# Generated by Django 6.0.8 on 2026-09-05 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('micro_internships', '0001_initial'),
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='microinternship',
            name='required_skills',
            field=models.ManyToManyField(blank=True, related_name='micro_internships', to='skills.skill'),
        ),
    ]
