# Generated by Django 6.0.8 on 2026-09-05 11:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('industries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('opportunity_type', models.CharField(choices=[('INTERNSHIP', 'Internship'), ('JOB', 'Full-time Job'), ('MICRO_INTERNSHIP', 'Micro-Internship'), ('PROJECT', 'Industry-Academia Project')], default='INTERNSHIP', max_length=30)),
                ('description', models.TextField()),
                ('location', models.CharField(default='Remote', max_length=255)),
                ('is_remote', models.BooleanField(default=True)),
                ('stipend_or_salary', models.CharField(blank=True, default='Competitive', max_length=100)),
                ('application_deadline', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active / Accepting Applications'), ('CLOSED', 'Closed')], default='ACTIVE', max_length=20)),
                ('openings_count', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('industry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opportunities', to='industries.industryprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
