# Generated by Django 6.0.8 on 2026-09-05 11:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('channel', models.CharField(choices=[('IN_APP', 'In-App'), ('EMAIL', 'Email'), ('SMS', 'SMS'), ('WHATSAPP', 'WhatsApp'), ('PUSH', 'Push')], default='IN_APP', max_length=20)),
                ('type', models.CharField(choices=[('APPLICATION_UPDATE', 'Application Update'), ('NEW_OPPORTUNITY', 'New Opportunity'), ('ASSESSMENT_RESULT', 'Assessment Result'), ('MENTORSHIP_INVITE', 'Mentorship Invite'), ('SYSTEM_ALERT', 'System Alert')], default='SYSTEM_ALERT', max_length=30)),
                ('is_read', models.BooleanField(default=False)),
                ('link_url', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
