'use client';

import React, { useState } from 'react';
import { NodePageShell } from '@/components/dashboard/node-page-shell';
import { Button, Badge, Card } from '@portal/ui';
import { Icon } from '@/components/ui/icon';

export default function AutoGeneratedPage() {
  const [filter, setFilter] = useState('all');
  const [search, setSearch] = useState('');

  const records = [
    {
      id: 'DOK-SIH-8042-01',
      title: 'Primary Operational Docket // Core Pipeline',
      entity: 'National Accreditation Verification Node',
      timestamp: 'OCT 2024 // ACTIVE',
      status: 'VERIFIED & LOCKED',
      variant: 'success' as const,
      details: 'All cryptographic parameters, Merkle tree signatures, and AICTE curricular alignments validated.',
    },
    {
      id: 'DOK-SIH-8042-02',
      title: 'Secondary Diagnostic Telemetry // Reciprocity Stream',
      entity: 'Bilateral Academic-Industry Exchange Pod',
      timestamp: 'OCT 2024 // SYNCHRONIZED',
      status: 'UNDER ACTIVE AUDIT',
      variant: 'signal' as const,
      details: 'Continuous syntactic ingestion benchmarked against real-time industrial demand matrices.',
    },
    {
      id: 'DOK-SIH-8042-03',
      title: 'Governance Audit Trail // Ledger Commitment',
      entity: 'Apex Verification Bureau (Govt of India)',
      timestamp: 'OCT 2024 // CERTIFIED',
      status: 'IMMUTABLE RECORD',
      variant: 'default' as const,
      details: 'Sovereign verifiable credential issued in strict compliance with W3C DID v2.0 standards.',
    },
  ];

  const filtered = records.filter((r) => 
    r.title.toLowerCase().includes(search.toLowerCase()) || 
    r.entity.toLowerCase().includes(search.toLowerCase())
  );

  return (
    <NodePageShell
      nodeId="STU-8042 // CANDIDATE"
      nodeStatus="TIER 01 ACCREDITED"
      category="STUDENT PORTAL // ACADEMIC TALENT REPOSITORY"
      title="Career - Readiness"
      description="Student Portal - Career - Readiness module."
      actions={
        <>
          <Button variant="signal" size="sm">
            <Icon name="upload" size={14} className="mr-1" />
            Synchronize Docket
          </Button>
          <Button variant="outline" size="sm">
            <Icon name="download" size={14} className="mr-1" />
            Export Audit Ledger
          </Button>
        </>
      }
      kpis={[
        { label: 'Verified Modules', value: '16 / 18', delta: 'OPTIMAL', deltaType: 'success', subtext: 'Updated Today', icon: 'dashboard' },
        { label: 'Skill Benchmark', value: '86.4%', delta: '+4.1%', deltaType: 'success', subtext: 'Cohort Standard', icon: 'verified' },
        { label: 'Dossier Status', value: 'ACTIVE', delta: 'SYNCHRONIZED', deltaType: 'neutral', subtext: 'Root Validated', icon: 'token' },
        { label: 'National Percentile', value: 'TOP 10%', delta: 'AICTE TIER-1', deltaType: 'neutral', subtext: 'SIH-2024 Compliant', icon: 'shield' },
      ]}
    >
      {/* Control Ribbon */}
      <div className="bg-bg-surface border border-border-strong p-space-md flex flex-col sm:flex-row items-center justify-between gap-space-md">
        <div className="flex items-center gap-space-xs flex-wrap w-full sm:w-auto">
          {['all', 'active', 'archived'].map((tab) => (
            <button
              key={tab}
              onClick={() => setFilter(tab)}
              className={
                'px-3 py-1 font-label-mono text-xs uppercase border transition-colors ' +
                (filter === tab
                  ? 'bg-fg-primary text-bg-surface border-border-strong font-bold'
                  : 'bg-bg-subtle text-fg-muted border-border-hairline hover:text-fg-primary')
              }
            >
              {tab === 'all' ? 'All Telemetry (03)' : tab}
            </button>
          ))}
        </div>

        <div className="relative w-full sm:w-80">
          <input
            type="text"
            placeholder="Filter docket reference or keyword..."
            value={search}
            onChange={(e) => setSearch(e.target.value)}
            className="w-full h-9 px-3 pr-8 border border-border-strong bg-bg-canvas font-body-sm text-fg-primary focus:outline-none focus:ring-2 focus:ring-border-strong"
          />
          <Icon name="search" size={16} className="absolute right-2.5 top-2.5 text-fg-muted" />
        </div>
      </div>

      {/* Dockets Feed */}
      <div className="space-y-space-sm">
        {filtered.map((item) => (
          <Card key={item.id} className="hover:border-border-strong transition-colors">
            <div className="flex flex-col lg:flex-row lg:items-center justify-between gap-space-md">
              <div className="space-y-2 flex-1">
                <div className="flex items-center gap-2 flex-wrap font-label-mono text-xs">
                  <Badge variant={item.variant}>{item.status}</Badge>
                  <span className="font-mono text-fg-muted">{item.id}</span>
                  <span className="text-border-hairline">|</span>
                  <span className="text-fg-primary font-bold">{item.entity}</span>
                </div>

                <h2 className="font-headline-sm text-body-lg font-bold text-fg-primary">
                  {item.title}
                </h2>

                <p className="text-body-sm text-fg-muted font-sans">
                  {item.details}
                </p>

                <div className="flex items-center gap-space-md flex-wrap font-label-mono text-xs text-fg-muted">
                  <span>TIMESTAMP: <strong className="text-fg-primary">{item.timestamp}</strong></span>
                  <span>PROTOCOL: <strong className="text-status-success font-semibold">SIH-8042 COMPLIANT</strong></span>
                </div>
              </div>

              <div className="flex sm:flex-col items-end gap-2 shrink-0">
                <Button variant="signal" size="sm">Inspect Telemetry</Button>
                <Button variant="outline" size="sm">Audit Cryptographic Proof</Button>
              </div>
            </div>
          </Card>
        ))}
      </div>
    </NodePageShell>
  );
}
